from PIL import Image
import io

gif_path = "logo.gif"
out_prefix = "logo_anim"

img = Image.open(gif_path)

width, height = img.size
frames = []
frame_sizes = []
delays = []

for i in range(img.n_frames):
    img.seek(i)

    frame = img.convert("RGBA")
    buffer = io.BytesIO()
    frame.save(
        buffer,
        format="PNG",
        optimize=True
    )

    frames.append(buffer.getvalue())
    delays.append(img.info.get("duration", 100))

with open(out_prefix + ".h", "w") as h:
    h.write(f"""#pragma once
// GENERATED BY `gen_logo_gif.py` DO NOT TOUCH

#include <stdint.h>

#define LOGO_ANIM_WIDTH {width}
#define LOGO_ANIM_HEIGHT {height}
#define LOGO_ANIM_FRAME_COUNT {len(frames)}

typedef struct
{{
    const uint32_t* delays;
    const uint32_t* sizes;
    const uint8_t* const* frames;
}} LogoAnim;


extern const LogoAnim logo_anim;

""")

with open(out_prefix + ".c", "w") as c:
    c.write("// GENERATED BY `gen_logo_gif.py` DO NOT TOUCH\n\n")
    c.write('#include "' + out_prefix + '.h"\n\n')

    for i, data in enumerate(frames):
        c.write(
            f"static const uint8_t frame_{i}[] = {{\n"
        )

        for j in range(0, len(data), 16):
            chunk = data[j:j+16]
            c.write(
                "    " +
                ", ".join(f"0x{x:02x}" for x in chunk) +
                ",\n"
            )

        c.write("};\n\n")

    c.write("static const uint32_t delays[] = {\n")
    for d in delays:
        c.write(f"    {d},\n")
    c.write("};\n\n")

    c.write("static const uint32_t sizes[] = {\n")
    for f in frames:
        c.write(f"    {len(f)},\n")
    c.write("};\n\n")

    c.write("static const uint8_t* const frames[] = {\n")
    for i in range(len(frames)):
        c.write(f"    frame_{i},\n")
    c.write("};\n\n")

    c.write(f"""
const LogoAnim logo_anim = {{
    .delays = delays,
    .sizes = sizes,
    .frames = frames
}};
""")
