#pragma once
// GENERATED BY `gen_logo_gif.py` DO NOT TOUCH

#include <stdint.h>

#define LOGO_ANIM_WIDTH 756
#define LOGO_ANIM_HEIGHT 92
#define LOGO_ANIM_FRAME_COUNT 5

typedef struct
{
    const uint32_t* delays;
    const uint32_t* sizes;
    const uint8_t* const* frames;
} LogoAnim;


extern const LogoAnim logo_anim;

