// GENERATED BY `gen_assets.py` DO NOT TOUCH

#pragma once

#include <stdint.h>

typedef struct
{
    const uint32_t* delays;
    const uint32_t* sizes;
    const uint8_t* const* frames;
} AnimImg;

#define LOGO_ANIM_WIDTH 756
#define LOGO_ANIM_HEIGHT 92
#define LOGO_ANIM_FRAME_COUNT 5

extern const AnimImg logo_anim;

#define APP_ICON_BYTES 603
extern const uint8_t app_icon[APP_ICON_BYTES];

#define MC_FONT_BYTES 19996
extern const uint8_t mc_font[MC_FONT_BYTES];
