from PIL import Image
import io


out_prefix = "assets"

header = open(out_prefix  + ".h", "w")
source = open(out_prefix  + ".c", "w")

header.write('// GENERATED BY `gen_assets.py` DO NOT TOUCH\n\n')
header.write('#pragma once\n\n')
header.write('#include <stdint.h>\n')
header.write("""
typedef struct
{
    const uint32_t* delays;
    const uint32_t* sizes;
    const uint8_t* const* frames;
} AnimImg;
""")

source.write('// GENERATED BY `gen_assets.py` DO NOT TOUCH\n\n')
source.write('#include "' + out_prefix + '.h"\n')

def write_bytes(name, data, static = True):
    source.write(
        f"\n{'static ' if static else ''}const uint8_t {name}[] = {{\n"
    )

    for j in range(0, len(data), 16):
        chunk = data[j:j+16]
        source.write(
            "    " +
            ", ".join(f"0x{x:02x}" for x in chunk) +
            ",\n"
        )

    source.write("};\n")

def save_gif(path, name):
    name_upper = name.upper()
    img = Image.open(path)
    width, height = img.size
    frames = []
    frame_sizes = []
    delays = []

    for i in range(img.n_frames):
        img.seek(i)

        frame = img.convert("RGBA")
        buffer = io.BytesIO()
        frame.save(
            buffer,
            format="PNG",
            optimize=True
        )

        frames.append(buffer.getvalue())
        delays.append(img.info.get("duration", 100))

    header.write(f"""
#define {name_upper}_WIDTH {width}
#define {name_upper}_HEIGHT {height}
#define {name_upper}_FRAME_COUNT {len(frames)}

extern const AnimImg {name};
""")

    for i, data in enumerate(frames):
        write_bytes(f"{name}_frame_{i}", data)

    source.write(f"static const uint32_t {name}_delays[] = {{\n")
    for d in delays:
        source.write(f"    {d},\n")
    source.write("};\n\n")

    source.write(f"static const uint32_t {name}_sizes[] = {{\n")
    for f in frames:
        source.write(f"    {len(f)},\n")
    source.write("};\n\n")

    source.write(f"static const uint8_t* const {name}_frames[] = {{\n")
    for i in range(len(frames)):
        source.write(f"    {name}_frame_{i},\n")
    source.write("};\n")

    source.write(f"""
const AnimImg {name} = {{
    .delays = {name}_delays,
    .sizes = {name}_sizes,
    .frames = {name}_frames
}};
""")

def save_binary(path, name):
    name_upper = name.upper()

    f = open(path, "rb").read()

    header.write(f"""
#define {name_upper}_BYTES {len(f)}
extern const uint8_t {name}[{name_upper}_BYTES];
""")
    write_bytes(name, f, False)

save_gif("logo.gif", "logo_anim")
save_binary("icon.png", "app_icon")
save_binary("minecraft.ttf", "mc_font")

header.close()
source.close()
